-- SQLite

CREATE TABLE DONATION
(
  BRAND_NUM    TEXT NOT NULL,
  TARGET_NUM   REAL NULL    ,
  MEMBERSHIP   TEXT NULL    ,
  MONTH_AMOUNT TEXT NULL    ,
    CONSTRAINT FK_MEMBER_TO_DONATION
    FOREIGN KEY (BRAND_NUM)
    REFERENCES MEMBER (BRAND_NUM)
);

CREATE TABLE HOURS
(
  BRAND_NUM TEXT NOT NULL,
  OPEN      TEXT NULL    ,
  BREAKTIME TEXT NULL    ,
  CLOSED    TEXT NULL    ,
  DAYOFF    TEXT NULL    ,
    CONSTRAINT FK_MEMBER_TO_HOURS
    FOREIGN KEY (BRAND_NUM)
    REFERENCES MEMBER (BRAND_NUM)
);

CREATE TABLE MEMBER
(
  BRAND_NUM  TEXT NOT NULL,
  BRAND_NAME TEXT NOT NULL,
  NAME       TEXT NULL    ,
  TELL       REAL NULL    ,
  PRIMARY KEY (BRAND_NUM)
);

CREATE TABLE MEMBER_TARGET
(
  BRAND_NUM TEXT NOT NULL,
  TARGET_ID TEXT NULL    ,
    CONSTRAINT FK_MEMBER_TO_MEMBER_TARGET
    FOREIGN KEY (BRAND_NUM)
    REFERENCES MEMBER (BRAND_NUM)
    CONSTRAINT FK_TARGET_TYPE_TO_MEMBER_TARGET
    FOREIGN KEY (TARGET_ID)
    REFERENCES TARGET_TYPE (TARGET_ID)
);

CREATE TABLE MENU
(
  BRAND_NUM TEXT NOT NULL,
  SERVICE   TEXT NULL    ,
  MENULIST       NULL    ,
  PRIMARY KEY (SERVICE)
    CONSTRAINT FK_MEMBER_TO_MENU
    FOREIGN KEY (BRAND_NUM)
    REFERENCES MEMBER (BRAND_NUM)
);

CREATE TABLE REGION
(
  REGION    TEXT NOT NULL,
  ADDRESS   TEXT NULL    ,
  BRAND_NUM TEXT NOT NULL,
    CONSTRAINT FK_MEMBER_TO_REGION
    FOREIGN KEY (BRAND_NUM)
    REFERENCES MEMBER (BRAND_NUM)
);

CREATE TABLE TARGET_TYPE
(
  TARGET_ID   TEXT NOT NULL,
  TARGET_TYPE TEXT NULL    ,
  PRIMARY KEY (TARGET_ID)
);


INSERT INTO MEMBER SELECT rowid,상호명,이름,연락처 FROM good_data ;
INSERT INTO REGION SELECT 지역,주소,rowid FROM good_data;
INSERT INTO DONATION SELECT rowid,제공대상1,후원회원,월후원액 FROM good_data;