-- SQLite

-- CREATE TABLE COMPANY(
-- ID REAL NOT NULL,
-- NAME TEXT   NOT NULL,
-- AGE REAL NOT NULL,
-- ADDRESS TEXT,
-- SALARY REAL );

-- CREATE TABLE DEPARTMENT(
-- ID REAL NOT NULL,
-- DEPT CHAR(50) NOT NULL,
-- EMP_ID REAL NOT NULL );

-- DROP TABLE DEPARTMENT;

-- ALTER TABLE COMPANY RENAME TO OLD_COMPANY;
-- ALTER TABLE OLD_COMPANY ADD COLUMN SEX TEXT;

-- INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS, SALARY) VALUES (1, 'Paul',32,'California', 20000);
-- INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS, SALARY) VALUES (2, 'Allen', 25, 'Texas', 15000);
-- INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS, SALARY) VALUES (3, 'Teddy', 23, 'Norway', 20000);
-- INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS, SALARY) VALUES (4, 'Mark', 25, 'Rich-Mond', 65000);
-- INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS, SALARY) VALUES (5, 'David', 27, 'Texas', 85000);
-- INSERT INTO COMPANY (ID,NAME,AGE,ADDRESS, SALARY) VALUES (6, 'Kim', 22, 'South-Hall', 45000);
-- INSERT INTO COMPANY VALUES (6, 'James', 24, 'Houston', 10000);
-- INSERT INTO COMPANY VALUES (7, 'James', 24, 'Houston', 10000);

SELECT * FROM COMPANY;
SELECT ID, NAME, SALARY FROM COMPANY;
SELECT tbl_name FROM sqlite_master;
SELECT sql FROM sqlite_master;

INSERT INTO OLD_COMPANY (ID,NAME,AGE,ADDRESS,SALARY)
SELECT ID, NAME,AGE,ADDRESS,SALARY FROM COMPANY ;

DELETE FROM OLD_COMPANY WHERE ID=7;
UPDATE OLD_COMPANY SET ADDRESS='Texas' WHERE ID=6;
UPDATE OLD_COMPANY SET ADDRESS='Seoul',SALARY=20000;

DELETE FROM OLD_COMPANY;