-- SQLite


CREATE TABLE AUTHORITY
(
  NAME    TEXT NULL    ,
  CODE_ID TEXT NOT NULL,
  PRIMARY KEY (CODE_ID)
);

CREATE TABLE DEPARTMENT
(
  DEP_ID TEXT NOT NULL,
  NAME   TEXT NULL    ,
  PRIMARY KEY (DEP_ID)
);

CREATE TABLE FILE
(
  IMAGE     TEXT NOT NULL,
  CONT_CODE TEXT NOT NULL,
  PRIMARY KEY (IMAGE),
    CONSTRAINT FK_MULTI_BOARD_TO_FILE
    FOREIGN KEY (CONT_CODE)
    REFERENCES MULTI_BOARD (CONT_CODE)
);

CREATE TABLE HOBBY
(
  NAME     TEXT NULL    ,
  HOBBY_ID TEXT NOT NULL,
  PRIMARY KEY (HOBBY_ID)
);

CREATE TABLE LOG_HISTORY
(
  MEMBER_ID   TEXT NOT NULL,
  LOGIN_TIME  TEXT NULL    ,
  LOGOUT_TIME TEXT NULL ,
    CONSTRAINT FK_MEMBER_TO_LOG_HISTORY
    FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBER (MEMBER_ID)   
);

CREATE TABLE MEMBER
(
  MEMBER_ID TEXT NOT NULL,
  NAME      TEXT NULL    ,
  AGE       REAL NULL    ,
  ADDRESS   TEXT NULL    ,
  SALARY    REAL NULL    ,
  DEP_ID    TEXT NOT NULL,
  PRIMARY KEY (MEMBER_ID),
    CONSTRAINT FK_DEPARTMENT_TO_MEMBER
    FOREIGN KEY (DEP_ID)
    REFERENCES DEPARTMENT (DEP_ID)
);

CREATE TABLE MEMBER_AUTHORITY
(
  MEMBER_ID TEXT NOT NULL,
  CODE_ID   TEXT NOT NULL,
    CONSTRAINT FK_MEMBER_TO_MEMBER_AUTHORITY
    FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBER (MEMBER_ID)
    CONSTRAINT FK_AUTHORITY_TO_MEMBER_AUTHORITY
    FOREIGN KEY (CODE_ID)
    REFERENCES AUTHORITY (CODE_ID)
);

CREATE TABLE MEMBER_HOBBY
(
  MEMBER_ID TEXT NOT NULL,
  HOBBY_ID  TEXT NOT NULL,
    CONSTRAINT FK_MEMBER_TO_MEMBER_HOBBY
    FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBER (MEMBER_ID)
    CONSTRAINT FK_HOBBY_TO_MEMBER_HOBBY
    FOREIGN KEY (HOBBY_ID)
    REFERENCES HOBBY (HOBBY_ID)
);

CREATE TABLE MULTI_BOARD
(
  TITLE     TEXT NULL    ,
  CONTENTS  TEXT NULL    ,
  CONT_CODE TEXT NOT NULL,
  MEMBER_ID TEXT NOT NULL,
  PRIMARY KEY (CONT_CODE),
    CONSTRAINT FK_MEMBER_TO_MULTI_BOARD
    FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBER (MEMBER_ID)
);

CREATE TABLE ORGANIZATION
(
  ORG_NUM        TEXT NOT NULL,
  ORG_NAME       TEXT NULL    ,
  PARENT_ORG_NUM TEXT NULL    ,
  PRIMARY KEY (ORG_NUM),
    CONSTRAINT FK_ORGANIZATION_TO_ORGANIZATION
    FOREIGN KEY (PARENT_ORG_NUM)
    REFERENCES ORGANIZATION (ORG_NUM)
);

CREATE TABLE PROJECT
(
  NAME      TEXT NULL    ,
  DATE      TEXT NULL    ,
  MEMBER_ID TEXT NOT NULL,
    CONSTRAINT FK_TEACHER_TO_PROJECT
    FOREIGN KEY (MEMBER_ID)
    REFERENCES TEACHER (MEMBER_ID)
);

CREATE TABLE TEACHER
(
  MEMBER_ID  TEXT NOT NULL,
  NAME       TEXT NULL    ,
  ADDRESS    TEXT NULL    ,
  EXPERIENCE TEXT NULL    ,
  TELL       TEXT NULL    ,
  SUBJECT    TEXT NULL    ,
  PRIMARY KEY (MEMBER_ID) ,
    CONSTRAINT FK_MEMBER_TO_TEACHER
    FOREIGN KEY (MEMBER_ID)
    REFERENCES MEMBER (MEMBER_ID)
);


INSERT INTO MEMBER VALUES ('ID_P', 'Paul','California', 20000,'IT',

