-- SQLite
CREATE TABLE DEPARTMENT
(
  DEPARTMENT_ID TEXT NOT NULL,
  NAME          TEXT NULL    ,
  PRIMARY KEY (DEPARTMENT_ID)
);

CREATE TABLE HOBBY
(
  NAME     TEXT NOT NULL,
  HOBBY_ID text NOT NULL,
  PRIMARY KEY (HOBBY_ID)
);


CREATE TABLE MEMBER_HOBBY
(
  MEMBER_ID text NOT NULL,
  HOBBY_ID  text NOT NULL
    CONSTRAINT FK_MEMBER_TO_MEMBER_HOBBY
    REFERENCES MEMBER (MEMBER_ID)
);



INSERT INTO MEMBER VALUES ('P_IT', 'Paul', 32, 'California', 20000, 'IT Billing') ;
INSERT INTO MEMBER VALUES ('A_E', 'Allen', 25, 'Texas', 15000, 'Engineering') ;
INSERT INTO MEMBER VALUES ('T_IT', 'Teddy', 23, 'Norway', 20000, 'IT Billing') ;
INSERT INTO MEMBER VALUES ('J_IT','James', 44, 'Norway', 5000, 'IT Billing') ;


INSERT INTO HOBBY VALUES ('Walk' , 'h1') ;
INSERT INTO HOBBY VALUES ('Climbing' , 'h2') ;
INSERT INTO HOBBY VALUES ('Read' , 'h3') ;

INSERT INTO MEMBER_HOBBY VALUES ('P_IT' , 'h1');
INSERT INTO MEMBER_HOBBY VALUES ('P_IT' , 'h2');
INSERT INTO MEMBER_HOBBY VALUES ('P_IT' , 'h3');
INSERT INTO MEMBER_HOBBY VALUES ('A_E' , 'h1');
INSERT INTO MEMBER_HOBBY VALUES ('A_E' , 'h3');
INSERT INTO MEMBER_HOBBY VALUES ('T_IT' , 'h2');
INSERT INTO MEMBER_HOBBY VALUES ('T_IT' , 'h3');
INSERT INTO MEMBER_HOBBY VALUES ('J_IT' , 'h1');

INSERT INTO DEPARTMENT VALUES ('IT','IT BILLING');
INSERT INTO DEPARTMENT VALUES ('ENGN','ENGINEERING');

--DEPARTMENT_ID 값이 달라서 변경
UPDATE MEMBER SET DEPARTMENT_ID='IT' WHERE DEPARTMENT_ID='IT Billing' ;
UPDATE MEMBER SET DEPARTMENT_ID='ENGN' WHERE DEPARTMENT_ID='Engineering' ;

--JOIN
SELECT MEMBER.NAME, DEPARTMENT.NAME FROM MEMBER, DEPARTMENT
WHERE MEMBER.DEPARTMENT_ID = DEPARTMENT.DEPARTMENT_ID;


--해보기2

--EMAIL 칼럼 추가 
ALTER TABLE MEMBER ADD COLUMN EMAIL;
--EMAIL 값 추가
UPDATE MEMBER SET EMAIL='paul01@gmail.com' WHERE MEMBER_ID='P_IT' ;
UPDATE MEMBER SET EMAIL='texas@imfblog.org' WHERE MEMBER_ID='A_E' ;
UPDATE MEMBER SET EMAIL='norway@iotm.com' WHERE MEMBER_ID='T_IT' ;


CREATE TABLE AUTHORITY
(
  CODE_ID   TEXT NULL    ,
  CODE_NAME TEXT NULL    ,
  PRIMARY KEY (CODE_ID)
);

--MEMBER 테이블 수정
DROP TABLE MEMBER ;

CREATE TABLE MEMBER
(
  MEMBER_ID     text NOT NULL,
  NAME          text NULL    ,
  AGE           REAL NULL    ,
  ADDRESS       TEXT NULL    ,
  SALARY        REAL NOT NULL,
  DEPARTMENT_ID TEXT NOT NULL,
  CODE_ID   TEXT NULL    ,
  PRIMARY KEY (MEMBER_ID)
  CONSTRAINT FK_DEPARTMENT_TO_MEMBER
    FOREIGN KEY (DEPARTMENT_ID)
    REFERENCES DEPARTMENT (DEPARTMENT_ID)
     CONSTRAINT FK_AUTHORITY_TO_MEMBER
    FOREIGN KEY (CODE_ID)
    REFERENCES AUTHORITY (CODE_ID)
);

INSERT INTO AUTHORITY VALUES ('code1' , 'GUEST');
INSERT INTO AUTHORITY VALUES ('code2' , 'ADMIN');
INSERT INTO AUTHORITY VALUES ('code3' , 'MANAGER');

UPDATE MEMBER SET CODE_ID='code1' WHERE MEMBER_ID='P_IT' ;

